config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    shared: "users/shared",
    unlocks: "users/unlocks",
    registrations: "users/registrations",
  }

  resources :dashboard, :clients, :organisations, :items, :invoice_settings

  resources :invoices do 
    resources :items
    resource :payments
    resource :send_invoices
  end

  root to: "dashboard#index"

end

app/models/invoice.rb
class Invoice
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :organisation
  belongs_to :client
  belongs_to :company
  has_many :items, autosave: true
  has_many :payments

  field :number, type: Integer
  field :date_of_issue, type: DateTime
  field :po_number, type: String
  field :discount, type: Integer
  field :note, type: String
  field :terms, type: String
  field :total, type: Float

  validates :number, presence: true
  validates :date_of_issue, presence: true
  validates :terms, presence: true

  def calculate_items_totals
    self.items.sum :total
  end

  def update_total
    self.total = calculate_items_totals
    self.save
  end

  def self.total
    Invoice.all.sum :total
  end

  def total_amount_paid
    self.payments.sum :amount
  end

  def total_amount_due
    unless total.nil?
      total - total_amount_paid
    end
  end

  def format_date
    self.date_of_issue = self.date_of_issue.strftime("%d/%m/%Y %H:%M")
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
		@invoices = Invoice.all.page params[:page]
  end

  def new
  	@invoice = Invoice.new
    @invoice_setting = InvoiceSetting.first || begin 
      OpenStruct.new(terms:nil, notes:nil)
    end
  end

  def create
  	@invoice = Invoice.new(invoice_params)

  	if @invoice.save
      redirect_to invoice_url(@invoice)
  	else
  		render 'new'
  	end
  end

  def edit
    @invoice = Invoice.find(params[:id])
    # change format so calendar can pre-populate
    @invoice.format_date
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoice_params)
      redirect_to invoice_url(@invoice)
    else
      render 'edit'
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    redirect_to invoices_path
  end

  private

  def invoice_params
  	params.require(:invoice).permit(
      :id,
      :client_id, 
      :organisation_id, 
      :number, 
      :date_of_issue, 
      :po_number, 
      :discount, 
      :note,
      :terms,
      {items: [:qty, :description, :item_kind_id, :price]}
    )
  end
end

app/views/invoices/_form.html.erb
<div class="panel-body">
  <div class="row header-row">
    <div class="col-md-7">
      <div class="form-group form-inline">
        <label>Client</label>
        <%= select("invoice", "client_id", Client.all.collect {|p| [ p.first_name, p.id ] }, {prompt: 'Select Client'}, class: 'form-control client-field', 
                   required: true) %>
               </div>
             </div>
             <div class="col-md-5">
               <div class="form-inline">
                 <div class="invoice-header">
                   <p>
                   <div class="form-group">
                     <label>Invoice Number</label>
                     <div class="input-group">
                       <div class="input-group-addon">#</div>
                       <%= f.text_field :number, class: 'form-control invoice-field', required: true, value: generate_invoice_number  %>
                     </div>
                   </div>
                   </p>

                   <p>
                   <div class="form-group">
                     <label>Date of Isssue</label>
                     <div class='input-group date' id='datetimepicker8'>
                       <%= f.text_field :date_of_issue, class: 'form-control', required: true %>
                       <span class="input-group-addon">
                         <span class="fa fa-calendar">
                         </span>
                       </span>
                     </div>
                   </div>
                   </p>
                   <p>
                   <div class="form-group">
                     <label>PO Number</label>
                     <%= f.text_field :po_number, class: 'form-control' %>
                   </div>
                   </p>

                   <p>
                   <div class="form-group">
                     <label>Discount</label>
                     <div class="input-group">
                       <%= f.text_field :discount, class: 'form-control discount-field', placeholder: '0' %>
                       <div class="input-group-addon">%</div>
                     </div>
                   </div>
                   </p>
                 </div>
               </div>
             </div>
           </div>

           <div class="row items-row">
             <div class="col-md-12">
               <table class="table table-bordered">
                 <thead>
                   <tr class="active">
                     <th>Qty</th>
                     <th>Kind</th>
                     <th>Description</th>
                     <th>Price</th>
                     <th>Total</th>
                     <th></th>
                   </tr>
                 </thead>
                 <tbody id="item-list">

                 </tbody>
                 <tfoot>
                   <tr class="active">
                     <td colspan="6">
                       <%= link_to new_invoice_item_path(invoice_id: @invoice.id), class: 'btn btn-xs btn-success', role: 'button', id: 'add_line', 
                         remote: true do %>
                         <i class="fa fa-plus"></i>Add Line
                       <% end %>
                     </td>
                   </tr>
                 </tfoot>
               </table>
             </div>
           </div>

           <div class="row">
             <div class="col-md-8">

             </div>
             <div class="col-md-4">
               <table class="table pull-right">
                 <tbody>
                 <tr>
                   <td>Invoice Total</td>
                   <td id="total">£0.00</td>
                 </tr>
                 <tr>
                   <td>Paid to Date</td>
                   <td id="paid">£0.00</td>
                 </tr>
                 <tfoot>
                   <tr class="active">
                     <td><b>Balance (GBP)</b></td>
                     <td><b id="balance">£0.00</b></td>
                   </tr>
                 </tfoot>
                 </tbody>
               </table>
             </div>
           </div>

           <div class="row notes-row">
             <div class="col-md-8">
               <div class="form-group">
                 <label>Terms (<a href="">Set default</a>)</label>
                 <%= f.text_area :terms, class: 'form-control', rows: 3, required: true %>
               </div>
             </div>
             <div class="col-md-4">
               <div class="form-group">
                 <label>Notes</label>
                 <%= f.text_area :note, class: 'form-control', rows: 3 %>
               </div>
             </div>
           </div>

           <hr>

           <div class="clearfix">
             <%= f.submit "Save Draft", class: 'btn btn-success pull-right form-btn' %>
             <button type="reset" class="btn btn-default pull-right form-btn">Cancel</button>
           </div>
         </div>

app/views/invoices/index.html.erb
<section id="main-content" class="animated fadeInUp">


  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Data Tables</h3>
          <div class="actions pull-right">
            <i class="fa fa-expand"></i>
            <i class="fa fa-chevron-down"></i>
            <i class="fa fa-times"></i>
          </div>
        </div>
        <div class="panel-body">
          <% if Invoice.empty? then %>
            <p class="text-danger empty_record">There are no saved invoices to show</p>
          <% else %>
            <table id="invoice-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th>Invoice #</th>
                  <th>Organisation</th>
                  <th>Date</th>
                  <th>Amount</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
              <% @invoices.each do |invoice| %>
                <tr>
                  <td><%= link_to add_invoice_prefix(invoice.number), invoice_url(invoice.id), class: "text-link" %></td>
                  <td><%= invoice.client.organisation.name %></td>
                  <td><%= invoice.created_at.to_formatted_s(:long) %></td>
                  <td class='invoice-total'><%= to_currency(invoice.total) %> </td>
                  <td class="text-muted">draft</td>
                  <td>
                    <%= link_to "view", invoice_url(invoice.id), class: "btn btn-xs btn-square btn-default view", role: "button" %>
                    <%= link_to "edit", edit_invoice_url(invoice.id), class: "btn btn-xs btn-square btn-info edit", role: "button" %>
                    <%= link_to "delete", invoice_url(invoice), method: :delete, data: {confirm: 'Are you sure?'}, 
                      class: "btn btn-xs btn-square btn-danger delete", role: "button" %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          <% end %>

          <div class="row">
            <div class="col-md-8">
              <%= paginate @invoices %> 
            </div>
            <div class="col-md-4">
              <p class="text-right invoice_totals"><b>Invoice totals:</b> &nbsp; <%= to_currency(Invoice.total) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <%= link_to new_invoice_path, class: 'btn btn-block btn-success create-invoice', role: 'button' do %>
        <i class="fa fa-check"></i> Create Invoice
      <% end %>
    </div>
  </div>
</section>

app/views/invoices/new.html.erb
<div class="modal fade load-new-invoice-settings" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
 <div class="modal-dialog modal-md">
   <div class="modal-content">
    <div id="modal-body">
      <%= render 'invoice_settings/form' %>
    </div>
   </div>
 </div>
</div>

<div id="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">New Invoice</h3>
          <div class="actions pull-right">
            <i class="fa fa-expand"></i>
            <i class="fa fa-chevron-down"></i>
            <i class="fa fa-times"></i>
          </div>
        </div>

        <% @invoice.errors.full_messages.each do |msg| %>
          <p class="text-danger"><%= msg %> </p>
        <% end %>

        <%= form_for @invoice do |f| %>
          <div class="panel-body">
            <div class="row header-row">
              <div class="col-md-7">
                <div class="form-group form-inline">
                  <label>Client</label>
                  <%= select("invoice", "client_id", Client.all.collect {|p| [ p.first_name, p.id ] }, {prompt: 'Select Client'}, class: 'form-control client-field', 
                             required: true) %>
                         </div>
                       </div>
                       <div class="col-md-5">
                         <div class="form-inline">
                           <div class="invoice-header">
                             <p>
                             <div class="form-group">
                               <label>Invoice Number</label>
                               <div class="input-group">
                                 <div class="input-group-addon">#</div>
                                 <%= f.text_field :number, class: 'form-control invoice-field', required: true, value: generate_invoice_number  %>
                               </div>
                             </div>
                             </p>

                             <p>
                             <div class="form-group">
                               <label>Date of Isssue</label>
                               <div class='input-group date' id='datetimepicker8'>
                                 <%= f.text_field :date_of_issue, class: 'form-control', required: true %>
                                 <span class="input-group-addon">
                                   <span class="fa fa-calendar">
                                   </span>
                                 </span>
                               </div>
                             </div>
                             </p>
                             <p>
                             <div class="form-group">
                               <label>PO Number</label>
                               <%= f.text_field :po_number, class: 'form-control' %>
                             </div>
                             </p>

                             <p>
                             <div class="form-group">
                               <label>Discount</label>
                               <div class="input-group">
                                 <%= f.text_field :discount, class: 'form-control discount-field', placeholder: '0' %>
                                 <div class="input-group-addon">%</div>
                               </div>
                             </div>
                             </p>
                           </div>
                         </div>
                       </div>
                     </div>

                     <div class="row items-row">
                       <div class="col-md-12">
                         <table class="table table-bordered">
                           <thead>
                             <tr class="active">
                               <th>Qty</th>
                               <th>Kind</th>
                               <th>Description</th>
                               <th>Price</th>
                               <th>Total</th>
                               <th></th>
                             </tr>
                           </thead>
                           <tbody id="item-list">

                           </tbody>
                           <tfoot>
                             <tr class="active">
                               <td colspan="6">
                                 <%= link_to new_invoice_item_path(invoice_id: @invoice.id), class: 'btn btn-xs btn-success', role: 'button', id: 'add_line', 
                                   remote: true do %>
                                   <i class="fa fa-plus"></i>Add Line
                                 <% end %>
                               </td>
                             </tr>
                           </tfoot>
                         </table>
                       </div>
                     </div>

                     <div class="row">
                       <div class="col-md-8">

                       </div>
                       <div class="col-md-4">
                         <table class="table pull-right">
                           <tbody>
                           <tr>
                             <td>Invoice Total</td>
                             <td id="total">£0.00</td>
                           </tr>
                           <tr>
                             <td>Paid to Date</td>
                             <td id="paid">£0.00</td>
                           </tr>
                           <tfoot>
                             <tr class="active">
                               <td><b>Balance (GBP)</b></td>
                               <td><b id="balance">£0.00</b></td>
                             </tr>
                           </tfoot>
                           </tbody>
                         </table>
                       </div>
                     </div>

                     <div class="row notes-row">
                       <div class="col-md-8">
                         <div class="form-group">
                           <label>
                            Terms (<%= link_to 'Set Default', '#', :data => {target: '.load-new-invoice-settings', toggle: 'modal'} %>)
                           </label>

                           
                           <%= f.text_area :terms, class: 'form-control', rows: 3, required: true, value: @invoice_setting.terms %>
                         </div>
                       </div>
                       <div class="col-md-4">
                         <div class="form-group">
                           <label>Notes</label>
                           <%= f.text_area :note, class: 'form-control', rows: 3, value: @invoice_setting.notes %>
                         </div>
                       </div>
                     </div>

                     <hr>

                     <div class="clearfix">
                       <%= f.submit "Save Draft", class: 'btn btn-success pull-right form-btn' %>
                     </div>
                   </div>
                 <% end %>
               </div>
             </div>

             <div class="col-md-3">
               <%= link_to new_client_path, class: 'btn btn-block btn-success', role: 'button' do %>
                 <i class="fa fa-check"></i> Create new Client
               <% end %>
             </div>
           </div>
         </div>
         <!--main content end

app/views/invoices/show.html.erb
<div class="row">
  <div class="modal fade bs-example-modal-md" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
      <div class="modal-content">

      </div>
    </div>
  </div>

  <div class="modal fade load-enter-payment" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

      </div>
    </div>
  </div>
</div>


<section id="main-wrapper" class="theme-default">
  <!--main content start-->
  <section class="main-content-wrapper">
    <div class="row action-row">
      <div class="col-md-5"><h1 class="invoice_no">Invoice: <%= add_invoice_prefix(@invoice.number) %></h1></div>
      <div class="col-md-7">
        <div class="clearfix">
          <div class="pull-right">

            <%= link_to 'Enter Payment', new_invoice_payments_path(@invoice), class: 'btn btn-sm btn-success', 
              role: 'button', :data => {target: '.load-enter-payment', toggle: 'modal'}  %>

            <%= link_to 'Send Invoice', new_invoice_send_invoices_path(@invoice), class: 'btn btn-sm btn-success', 
              role: 'button', :data => {target: '.bs-example-modal-md', toggle: 'modal'}  %>

            <%= link_to 'Edit', edit_invoice_url(@invoice.id), class: 'btn btn-sm btn-default', role: 'button'%>
          </div>
        </div>
      </div>
    </div>


    <div id="container">
      <div class="row">
        <div class="col-md-12">
          <div class="invoice_status text-muted text-center status-well">draft</div>
          <div class="invoice_status hidden text-muted text-center status-well">sent</div>
          <div class="invoice_status hidden text-muted text-center status-well">viewed</div>
          <div class="invoice_status hidden text-success text-center status-well">paid</div>
          <div class="invoice_status hidden text-warning text-center status-well">partial</div>
          <div class="invoice_status hidden text-danger text-center status-well">overdue</div>
          <div class="invoice_status hidden text-danger text-center status-well">disputed</div>
        </div>
      </div>

      <div class="row sender-details">
        <div class="col-md-8">
          <address>
            <p id="company_name"><%= current_user.company.name %></p>
            <p id="company_street_1"><%= current_user.company.street_1 %></p>
            <p id="company_street_2"><%= current_user.company.street_2 %></p>
            <p id="company_town"><%= current_user.company.town %></p>
            <p id="company_city"><%= current_user.company.city %></p>
            <p id="company_postcode"><%= current_user.company.post_code %></p>
          </address>
        </div>
        <div class="col-md-4">
          <div id="logo">Company Logo</div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <div class="client-address">
            <p id="org_name"><%= @invoice.client.organisation.name %></p>
            <p id="org_street_1"><%= @invoice.client.organisation.street_1 %></p>
            <p id="org_street_2"><%= @invoice.client.organisation.street_2 %></p>
            <p id="org_town"><%= @invoice.client.organisation.town %></p>
            <p id="org_city"><%= @invoice.client.organisation.city %></p>
            <p id="org_postcode"><%= @invoice.client.organisation.post_code %></p>
          </div>
        </div>
        <div class="col-md-4">
          <table class="table summary">
            <tbody>
            <tr>
              <td>Invoice #</td>
              <td id="invoice_number"><%= add_invoice_prefix(@invoice.number) %></td>
            </tr>
            <tr>
              <td>Invoice Date</td>
              <td id="invoice_date"><%= @invoice.date_of_issue.to_formatted_s(:long) %></td>
            </tr>
            <tr>
              <td>PO #</td>
              <td id="po"><%= @invoice.po_number %></td>
            </tr>
            <tfoot>
              <tr class="active">
                <td>Due</td>
                <td id="due"><%= to_currency(@invoice.total_amount_due) %></td>
              </tr>
            </tfoot>
            </tbody>
          </table>

        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <table class="table" id="items">
            <thead>
              <tr class="active">
                <th colspan="2">Task</th>
                <th class="text-center">Qty</th>
                <th class="text-center">Kind</th>
                <th class="text-center">Rate</th>
                <th class="text-center">Line Total</th>
              </tr>
            </thead>
            <tbody>
            <% @invoice.items.each do |item| %>
              <tr>
                <td class="description" colspan="2"><%= item.description %></td>
                <td class="item_qty text-center"><%= item.qty %></td>
                <td class="item_kind text-center"><%= item.item_kind.name %></td>
                <td class="item_price text-center"><%= to_currency(item.price) %></td>
                <td class="item_line_total text-center"><%= to_currency(item.total) %></td>
              </tr>
            <% end %>
            </tbody>
            <tfoot>
              <tr>
                <td colspan="4"></td>
                <td class="text-right">Total</td>
                <td class="text-center"><b id="total"><%= to_currency(@invoice.total) %> </b></td>
              </tr>
              <tr>
                <td colspan="4"></td>
                <td class="text-right">Amount Paid</td>
                <td class="text-center" id="amount-paid"><%= to_currency(@invoice.total_amount_paid) %></td>
              </tr>
              <tr>
                <td colspan="4"></td>
                <td class="text-right">Amount Due</td>
                <td class="text-center active" id="amount-due"><b><%= to_currency(@invoice.total_amount_due) %></b></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <aside id="invoice_terms">
            <p><b>Terms</b></p>
            <p><%= simple_format @invoice.terms %></p>
          </aside>
        </div>
      </div>

      <div class="row">
        <p class="powered text-center">This invoice system is powered by <b>KOCO</b></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div id="autobiography">
          <div class="well well-sm">
            <h4>Invoice autobiography</h4>

            <div class="complete-row">
              <hr>
              <div class="row bio-row">
                <div class="col-md-1"><span class="label label-default">Created</span></div>
                <div class="col-md-8 bio-status">Created by you.</div>
                <div class="col-md-3 bio-date text-right">30 Mar 2015, 7:04 AM</div>
              </div>
            </div>

            <div class="complete-row">
              <hr>
              <div class="row bio-row">
                <div class="col-md-1"><span class="label label-default">Updated</span></div>
                <div class="col-md-8 bio-status">Updated by you.</div>
                <div class="col-md-3 bio-date text-right">30 Mar 2015, 7:04 AM</div>
              </div>
            </div>

            <div class="complete-row">
              <hr>
              <div class="row bio-row">
                <div class="col-md-1"><span class="label label-default">Sent</span></div>
                <div class="col-md-8 bio-status">Sent by you.</div>
                <div class="col-md-3 bio-date text-right">30 Mar 2015, 7:04 AM</div>
              </div>
            </div>

            <div class="complete-row">
              <hr>
              <div class="row bio-row">
                <div class="col-md-1"><span class="label label-default">Viewed</span></div>
                <div class="col-md-8 bio-status">Viewed by John</div>
                <div class="col-md-3 bio-date text-right">30 Mar 2015, 7:04 AM</div>
              </div>
            </div>

            <div class="complete-row">
              <hr>
              <div class="row bio-row">
                <div class="col-md-1"><span class="label label-default">Payment</span></div>
                <div class="col-md-8 bio-status">Payment added by you. £9,740.00 of £9,740.00</div>
                <div class="col-md-3 bio-date text-right">30 Mar 2015, 7:04 AM</div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
  <!--main content end-->
</section>