config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    shared: "users/shared",
    unlocks: "users/unlocks",
    registrations: "users/registrations",
  }

  resources :dashboard, :clients, :organisations, :items, :invoice_settings

  resources :invoices do 
    resources :items
    resource :payments
    resource :send_invoices
  end

  root to: "dashboard#index"

end

app/views/shared/_contact_list.html.erb
<!--sidebar right start-->
<aside id="sidebar-right">
  <h4 class="sidebar-title">contact List</h4>
  <div id="contact-list-wrapper">
    <div class="heading">
        <ul>
            <li class="new-contact"><a href="javascript:void(0)"><i class="fa fa-plus"></i></a>
            </li>
            <li>
                <input type="text" class="search" placeholder="Search">
                <button type="submit" class="btn btn-sm btn-search"><i class="fa fa-search"></i>
                </button>
            </li>
        </ul>
    </div>

    <div id="contact-list">
        <ul>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                  <%= image_tag("avatar3.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Ashley Bell </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Sarasota, FL</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar1.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Brian Johnson </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> San Francisco, CA</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar2.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Chris Jones </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Brooklyn, NY</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar3.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Erica Hill </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Palo Alto, Ca</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar5.png", class: 'img-circle') %>
                  <i class="away animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Greg Smith </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> London, UK</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar6.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Jason Kendall</div>
                        <small class="location text-muted"><i class="icon-pointer"></i> New York, NY </small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar7.png", class: 'img-circle') %>
                  <i class="on animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Kristen Davis </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Greenville, SC</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar8.png", class: 'img-circle') %>
                  <i class="off animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Michael Shepard </div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Vancouver, BC</small>
                    </div>
                </div>
            </li>
            <li>
                <div class="row">
                    <div class="col-md-3">
                        <span class="avatar">
                        <%= image_tag("avatar9.png", class: 'img-circle') %>
                  <i class="off animated bounceIn"></i>
                </span>
                    </div>
                    <div class="col-md-9">
                        <div class="name">Paul Allen</div>
                        <small class="location text-muted"><i class="icon-pointer"></i> Savannah, GA</small>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div id="contact-user">
        <div class="chat-user active"><span><i class="icon-bubble"></i></span>
        </div>
        <div class="email-user"><span><i class="icon-envelope-open"></i></span>
        </div>
        <div class="call-user"><span><i class="icon-call-out"></i></span>
        </div>
    </div>
  </div>
</aside>
<!--/sidebar right end-->

app/views/shared/_header.html.erb
<header id="header">
  <!--logo start-->
  <div class="brand">
    <a href="index.html" class="logo">
      <i class="icon-layers"></i>
      <span>INVOICE</span>SYSTEM</a>
  </div>
  <!--logo end-->
  <ul class="nav navbar-nav navbar-left">
    <li class="toggle-navigation toggle-left">
    <button class="sidebar-toggle" id="toggle-left">
      <i class="fa fa-bars"></i>
    </button>
    </li>
    <li class="toggle-profile hidden-xs">
    <button type="button" class="btn btn-default" id="toggle-profile">
      <i class="icon-user"></i>
    </button>
    </li>
    <li class="hidden-xs hidden-sm">
    <input type="text" class="search" placeholder="Search project...">
    <button type="submit" class="btn btn-sm btn-search"><i class="fa fa-search"></i>
    </button>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown profile hidden-xs">
    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
      <span class="meta">
        <span class="avatar">
          <%= image_tag("profile.jpg", class: 'img-circle') %>
        </span>
        <span class="text">Kingsley Ijomah</span>
        <span class="caret"></span>
      </span>
    </a>
    <ul class="dropdown-menu animated fadeInRight" role="menu">
      <li>
      <span class="arrow top"></span>
      <h5>
        <span>80%</span>
        <small class="text-muted">Profile complete</small>
      </h5>
      <div class="progress progress-xs">
        <div class="progress-bar progress-bar" style="width: 80%">
        </div>
      </div>
      </li>
      <li class="divider"></li>
      <li>
      <a href="javascript:void(0);">
        <span class="icon"><i class="fa fa-user"></i>
      </span>My Account</a>
      </li>
      <li>
      <a href="javascript:void(0);">
        <span class="icon"><i class="fa fa-envelope"></i>
      </span>Messages</a>
      </li>
      <li>
      <a href="javascript:void(0);">
        <span class="icon"><i class="fa fa-cog"></i>
      </span>Settings</a>
      </li>
      <li class="divider"></li>
      <li>
      <%= link_to destroy_user_session_path, :method => :delete do %>
        <span class="icon"><i class="fa fa-sign-out"></i></span>Logout
      <% end %>
      </li>
    </ul>
    </li>
    <li class="toggle-fullscreen hidden-xs">
    <button type="button" class="btn btn-default expand" id="toggle-fullscreen">
      <i class="fa fa-expand"></i>
    </button>
    </li>
    <li class="toggle-navigation toggle-right">
    <button class="sidebar-toggle" id="toggle-right">
      <i class="fa fa-indent"></i>
    </button>
    </li>
  </ul>
</header>

app/views/shared/_page_header.html.erb
<div class="pageheader">
  <h1 id="crums-controller"><%= bread_crums_controller %></h1>
  <div class="breadcrumb-wrapper hidden-xs">
    <span class="label">You are here:</span>
    <ol class="breadcrumb">
      <% build_bread_crums.each do |crumb| %> 
        <li><%= crumb %></li>
      <% end %>
    </ol>
  </div>
</div>

app/views/shared/_side_menu.html.erb
<!--sidebar left start-->
<aside class="sidebar sidebar-left">
  <div class="sidebar-profile">
    <div class="avatar">
      <%= image_tag('profile.jpg', class: 'img-circle profile-image', alt: 'profile') %>
      <i class="on border-dark animated bounceIn"></i>
    </div>
    <div class="profile-body dropdown">
      <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><h4>Kingsley Ijomah <span class="caret"></span></h4></a>
      <small class="title">Software Eng.</small>
      <ul class="dropdown-menu animated fadeInRight" role="menu">
        <li class="profile-progress">
        <h5>
          <span>80%</span>
          <small>Profile complete</small>
        </h5>
        <div class="progress progress-xs">
          <div class="progress-bar progress-bar-primary" style="width: 80%">
          </div>
        </div>
        </li>
        <li class="divider"></li>
        <li>
        <a href="javascript:void(0);">
          <span class="icon"><i class="fa fa-user"></i>
        </span>My Account</a>
        </li>
        <li>
        <a href="javascript:void(0);">
          <span class="icon"><i class="fa fa-envelope"></i>
        </span>Messages</a>
        </li>
        <li>
        <a href="javascript:void(0);">
          <span class="icon"><i class="fa fa-cog"></i>
        </span>Settings</a>
        </li>
        <li class="divider"></li>
        <li>
        <a href="javascript:void(0);">
          <span class="icon"><i class="fa fa-sign-out"></i>
        </span>Logout</a>
        </li>
      </ul>
    </div>
  </div>
  <nav id="main_navigation">
    <h5 class="sidebar-header">Navigation</h5>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= "#{set_active_if_current controller: 'dashboard'}" %>">
      <%= link_to dashboard_index_path, :title => 'Dashboard' do %>
        <i class="fa fa-fw fa-tachometer"></i> Dashboard
      <% end %>
      </li>
      <li class="<%= "#{set_active_if_current controller: 'invoices'}" %>">
      <%= link_to invoices_path, :title => 'Invoices' do %>
        <i class="fa fa-fw fa-money"></i> Invoices
      <% end %>
      </li>
      <li class="<%= "#{set_active_if_current controller: 'clients'}" %>">
      <%= link_to clients_path, :title => 'Clients' do %>
        <i class="fa fa-fw fa-users"></i> Clients
      <% end %>
      </li>
    </ul>
  </nav>
</aside>
<!--sidebar left end-->