config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    shared: "users/shared",
    unlocks: "users/unlocks",
    registrations: "users/registrations",
  }

  resources :dashboard, :clients, :organisations, :items, :invoice_settings

  resources :invoices do 
    resources :items
    resource :payments
    resource :send_invoices
  end

  root to: "dashboard#index"

end

app/models/client.rb
class Client
	include Mongoid::Document
	include Mongoid::Timestamps

	belongs_to :organisation
	has_many :invoices

	validates :contact_type, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :tel, presence: true

	field :contact_type, type: Boolean
	field :first_name, type: String
	field :last_name, type: String
	field :email, type: String
	field :tel, type: String
	field :note, type: String
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController 
	def index
		@clients = Client.all.page params[:page]
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(clients_params)
		if @client.save
			redirect_to clients_path
		else
			render 'new'
		end
	end

	def edit
		@client = Client.find(params[:id])
	end

	def update
		@client = Client.find(params[:id])
		
		if @client.update(clients_params)
			redirect_to clients_path
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@client = Client.find(params[:id])
		@client.destroy

		redirect_to clients_path
	end

	private

	def clients_params
		params.require(:client).permit(:organisation_id, :contact_type, :first_name, :last_name, :email, :tel, :note)
	end
end

app/views/clients/_form.html.erb
<div id="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= title %></h3>
          <div class="actions pull-right">
            <i class="fa fa-expand"></i>
            <i class="fa fa-chevron-down"></i>
            <i class="fa fa-times"></i>
          </div>
        </div>
        <div class="panel-body">

          <div id="validation-errors">
            <% @client.errors.full_messages.each do |msg| %>
              <p class="text-danger"><%= msg %> </p>
            <% end %>
          </div>

          <%= form_for @client do |f| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= select("client", "organisation_id", Organisation.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Organisation'}, class: 'form-control') %>
                </div>

                <div class="form-group">
                  <%= f.select(:contact_type, [['Primary Contact', true], ['Secondary Contact', false]], {}, { class: 'form-control' }) %>
                </div>

                <div class="form-group">
                  <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name', id: 'first-name' %>
                </div>

                <div class="form-group">
                  <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name', id: 'last-name' %>
                </div>

                <div class="form-group">
                  <%= f.text_field :email, class: 'form-control', placeholder: 'Email', id: 'email' %>
                </div>

                <div class="form-group">
                  <%= f.text_field :tel, class: 'form-control', placeholder: 'Telephone', id: 'telephone' %>
                </div>

                <div class="form-group">
                  <%= f.text_area :note, class: 'form-control', placeholder: 'Internal Note', id: 'note' %>
                </div>
              </div>
            </div>

            <div class="clearfix">
              <%= f.submit "Save Client", class: 'btn btn-success pull-right' %>
              <button type="reset" class="btn btn-default pull-right reset">Cancel</button>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <div class="col-md-3">
      <%= link_to new_organisation_path, class: 'btn btn-block btn-success', role: 'button', 
        :data => {target: '.load-new-organisation', toggle: 'modal'} do %>
        <i class="fa fa-check"></i> Create new Organisation
      <% end %>
    </div>
  </div>

  <div class="modal fade load-new-organisation" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
      <div class="modal-content">


      </div>
    </div>
  </div>
</div>

app/views/clients/edit.html.erb
<%= render 'form', title: 'Edit Client' %>

app/views/clients/index.html.erb
<section id="main-content" class="animated fadeInUp">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Data Tables</h3>
          <div class="actions pull-right">
            <i class="fa fa-expand"></i>
            <i class="fa fa-chevron-down"></i>
            <i class="fa fa-times"></i>
          </div>
        </div>
        <div class="panel-body">
          <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>Organisation</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
            <% @clients.each do | client | %>
              <tr class="client-row">
                <td><a href="#" class="text-link"><%= client.organisation.name %></a></td>
                <td><%= client.first_name %></td>
                <td><%= client.last_name %></td>
                <td><%= client.email %></td>
                <td><%= client.tel %></td>
                <td>
                  <div class="row">
                    <div class="col-md-5">
                      <%= button_to "delete", client_path(:id => client.id), :method => :delete, class: 'btn btn-xs btn-square btn-danger delete_client', 
                        data: { confirm: 'Are you sure?' } %>
                    </div>
                    <div class="col-md-7">
                      <%= link_to 'edit', edit_client_path(client), class: 'btn btn-xs btn-square btn-primary edit_client', role: 'button' %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

          <%= paginate @clients %> 
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <%= link_to new_client_path, class: 'btn btn-block btn-success', role: 'button' do %>
        <i class="fa fa-check"></i> Create new Client
      <% end %>
    </div>
  </div>
</section>

app/views/clients/new.html.erb
<%= render 'form', title: 'Create Client' %>