config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    sessions: "users/sessions", 
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    shared: "users/shared",
    unlocks: "users/unlocks",
    registrations: "users/registrations",
  }

  resources :dashboard, :clients, :organisations, :items, :invoice_settings

  resources :invoices do 
    resources :items
    resource :payments
    resource :send_invoices
  end

  root to: "dashboard#index"

end

app/controllers/send_invoices_controller.rb
class SendInvoicesController < ApplicationController
  layout 'plain'

  def new
    @invoice = Invoice.find(params[:invoice_id])
  end 

  def create
    @invoice = Invoice.find params[:invoice_id]
    @client = @invoice.client
    InvoiceMailer.send_invoice_email(client: @client, invoice: @invoice).deliver_now
    redirect_to @invoice, notice: 'You have successfully sent invoice #0000' + @invoice.number.to_s + ' to ' + @client.organisation.name 
  end
end

app/views/send_invoices/new.html.erb
<p>
You are about to send invoice <span id="invoice_no"><%= add_invoice_prefix(@invoice.number) %></span> to
<b id="company"><%= @invoice.client.organisation.name %>.</b><br>
Please confirm or cancel below to complete transaction.
</p>

<div class="modal-footer">
  <%= form_for :send_invoice, url: invoice_send_invoices_path do |f| %>
    <%= hidden_field_tag 'invoice_id', value: @invoice.id %>
    <%= f.submit 'Confirm', class: 'btn btn-success' %> 
  <% end %>
</div>